### ISSUE TITLE
Tweets seem slow to update

### ISSUE THREAD

**Issue by mhamann** [MatthewRuddy/displaytweets#1]
After implementing this plugin on a site, the tweets seem to take between 4 and 5 hours to update instead of updating every few minutes as expected (I was thinking they would update at least every half-hour).

Is there a setting that needs to be changed to enable faster updates or is there perhaps a bug causing the updater not to run as frequently as intended?

**Comment by MatthewRuddy** [comment]
There was a bug that was causing this issue in the initial v1.0 of the plugin. It has since been fixed - have you updated to v1.0.2?

**Comment by mhamann** [comment]
We were running 1.0.1, but have now upgraded to 1.0.2, so we'll monitor it for improvement. Thanks!

**Comment by MatthewRuddy** [comment]
Should be resolved completely with v1.0.3 (just uploaded now) :)
