### ISSUE TITLE
# hastags not linking correctly.

### ISSUE THREAD

**Issue by Jonwicks25** [MatthewRuddy/displaytweets#2]
Line 501 needs to be updated. to the following
`$text = preg_replace( "/#(\w+)/", "<a href=\"http://twitter.com/search?q=%23\\1&src=hash\" target=\"_blank\">#\\1</a>", $text );`

As the old code is using the old API v1
`$text = preg_replace( "/#(\w+)/", "<a href=\"http://search.twitter.com/search?q=\\1\" target=\"_blank\">#\\1</a>", $text );`

**Comment by MatthewRuddy** [comment]
If you can submit a pull request I'll merge it for you.

**Comment by Jonwicks25** [comment]
Think I've done that right.. Kind of new to GitHub :)

**Comment by MatthewRuddy** [comment]
It's perfect, haha! It's merged.

Thanks! :)
