### ISSUE TITLE
Still not updating on wordpress

### ISSUE THREAD

**Issue by Jonwicks25** [MatthewRuddy/displaytweets#5]
Sorry to be a pain, updated to version v.1.0.3 and retested. Been over an hour and still not updating latest tweets. 

I have double checked it's not conflicting with any other plugins etc and 99% sure its not.

**Comment by MatthewRuddy** [comment]
Have you tried re-saving your settings? Might have to wait a few hours for the older cache to expire (from botched v1.0.2) and cache to be renewed.

I've been testing and it's been working perfectly.

**Comment by Jonwicks25** [comment]
aha, had to save the settings twice (think that was just my internet being stupid) after that much better. Thanks
